### ISSUE TITLE
JS file served by another domain

### ISSUE THREAD

**Issue by Arnapappo** [Aleksi44/wagtailyoast#2]
Is there an additional setting to run yoastworker when it is served by another domain (eg. aws s3)?
In my configuration all dist files are hosted in a aws s3 bucket and this make a 404 error.
I think the code line that raise the error is in wagtailyoast/static/wagtailyoast/src/js/common/Panel.js:13

**Comment by Aleksi44** [comment]
Hi @Arnapappo 

We can simply fix this by adding `STATIC_URL` to yoast context [here](https://github.com/Aleksi44/wagtailyoast/blob/master/wagtailyoast/wagtail_hooks.py#L17).

And replace "this.baseUrl" [here](https://github.com/Aleksi44/wagtailyoast/blob/master/wagtailyoast/static/wagtailyoast/src/js/common/WithContext.js#L9) by this value.

I can do an MR when I have some time. Otherwise, feel free to do so.

**Comment by diegoleft** [comment]
Is there a way to do this without edit the core files?
in django settings?

**Comment by Aleksi44** [comment]
No, I think the best way to deal with this problem would be to apply a fix as it is possible to retrieve the url of the static files with STATIC_URL from Django.

**Comment by Aleksi44** [comment]
@diegoleft @Arnapappo 

Fix here #6 

And avalaible here :

```
wagtailyoast==0.0.9
```

**Comment by aisamji** [comment]
The above fix does not resolve this issue. It changed line 13 in [Panel.js](https://github.com/Aleksi44/wagtailyoast/blob/master/wagtailyoast/static/wagtailyoast/src/js/common/Panel.js) as shown:

From this: ``this.workerUrl = `${this.baseUrl}/static/wagtailyoast/dist/js/yoastworker${this.context.version}.js`;``
To this: ``this.workerUrl = `${this.baseUrl}${this.context.staticUrl}wagtailyoast/dist/js/yoastworker${this.context.version}.js`;``

The issue this resolves is having a different root for static files than `/static/`. It still does not allow grabbing files from a different host such as when using an aws s3 bucket to host the static files.

**Comment by Aleksi44** [comment]
@aisamji 

If you use a different host with Django for your static files, you can set your `STATIC_URL` like this :

```
STATIC_URL = "https://your-static-files-host.com/path"
```

Does this solve your problem?

**Comment by aisamji** [comment]
No. This resulted in a URL that concatenated the `BASE_URL` and `STATIC_URL` like so:
```
https://my-website.comhttps://my-static-files-host.com/wagtailyoast/dist/js/yoastworker0.0.9.js
```

**Comment by Aleksi44** [comment]
I see :/

We should check if `STATIC_URL` contains a host and if yes, we remove baseUrl.
Does this sound good to you?

**Comment by aisamji** [comment]
Yes, that sounds like it would work.
